---

  - name: integration -  configure compliance
    shell: chef-compliance-ctl connect chef-server --non-interactive true --chef-app-id 'compliance_server' --auth-id 'Chef Server' --insecure true --compliance-url 'https://{{ fqdn }}'|grep ^CHEF_APP_ID
    register: results

  - name: save output to /etc/ansible/files/compliance_chef_app_id.sh
    local_action: copy content="{{ results.stdout }}" dest=/etc/ansible/files/compliance_chef_app_id.sh

  - name: reconfigure chef compliance
    command: chef-compliance-ctl reconfigure

  - name: restart chef compliance core
    command: chef-compliance-ctl restart core

  - name: copy compliance_chef_app_id.sh to chef server
    copy: src=/etc/ansible/files/compliance_chef_app_id.sh dest=/root/
    delegate_to: "{{ chef_server_inventory_name }}"

  - name: integration - configure chef server
    shell: bash /root/compliance_chef_app_id.sh|grep "^chef-compliance-ctl auth add"
    register: results
    delegate_to: "{{ chef_server_inventory_name }}"

  - name: save output to /etc/ansible/files/compliance_auth_add.sh
    local_action: copy content="{{ results.stdout }}" dest=/etc/ansible/files/compliance_auth_add.sh

  - name: integration - configure chef compliance
    script: /etc/ansible/files/compliance_auth_add.sh

  - name: reconfigure chef compliance
    command: chef-compliance-ctl reconfigure
