---
  - hosts: chefcompliance
    tasks:
     - name: get chef compliance package
       get_url: url=https://packages.chef.io/stable/el/7/chef-compliance-1.3.1-1.el7.x86_64.rpm dest=/root/

     - name: install chef compliance package
       yum: name=/root/chef-compliance-1.3.1-1.el7.x86_64.rpm state=present

     - name: reconfigure chef compliance
       command: chef-compliance-ctl reconfigure --accept-license
   
     - name: integration -  configure compliance
       shell: chef-compliance-ctl connect chef-server --non-interactive true --chef-app-id 'compliance_server' --auth-id 'Chef Server' --insecure true --compliance-url 'https://compliance01.example.com'|grep ^CHEF_APP_ID
       register: results

     - name: save output to /root/compliance_chef_app_id.sh
       local_action: copy content="{{ results.stdout }}" dest=/root/compliance_chef_app_id.sh
     
     - name: reconfigure chef compliance
       command: chef-compliance-ctl reconfigure

     - name: restart chef compliance core
       command: chef-compliance-ctl restart core

#  - hosts: chefserver
#    tasks:
#     - name: integration - configure chef server
#       script: /root/compliance_chef_app_id.sh|grep "^chef-compliance-ctl auth add"
#       register: results

#     - name: save output to /root/compliance_auth_add.sh
#       local_action: copy content="{{ results.stdout }}" dest=/root/compliance_auth_add.sh
  
#  - hosts: chefcompliance
#    tasks:

#     - name: integration - configure chef compliance
#       script: /root/compliance_auth_add.sh

#     - name: reconfigure chef compliance
#       command: chef-compliance-ctl reconfigure
