---
  - hosts: chefcompliance
    tasks:
     - name: get chef compliance package
       get_url: url=https://packages.chef.io/stable/el/7/chef-compliance-1.3.1-1.el7.x86_64.rpm dest=/root/

     - name: install chef compliance package
       yum: name=/root/chef-compliance-1.3.1-1.el7.x86_64.rpm state=present

     - name: reconfigure chef compliance
       command: chef-compliance-ctl reconfigure --accept-license
