---
  - hosts: infrahosts,apphosts
    roles:
      - democommon

  - include: chefserver.yaml
  - include: chefworkstaion.yaml
  - include: chefautomate.yaml
  - include: chefcompliance.yaml
  - include: configure_automate_environment.yaml
