---
  - hosts: workstation
    tasks:

     - name: install chefdk package
       yum: name=https://packages.chef.io/stable/el/7/chefdk-0.17.17-1.el7.x86_64.rpm  state=present

     - name: install additional packages
       yum: name={{ item }} state=present
       with_items:
         - git
         - vim

     - name: verify chefdk installation
       command: chef verify

     - name: configure system ruby
       shell: echo 'eval "$(chef shell-init bash)"' >> /etc/profile

  - hosts: chefserver
    tasks:

     - name: get key files - org validators and user keys
       fetch: src=/root/{{ item }} dest=/root/ flat=yes fail_on_missing=yes
       with_items:
         - chefroot.pem
         - delivery.pem
         - demoorg-validator.pem
         - autoorg-validator.pem