---
  - hosts: workstation
    tasks:

     - name: install chefdk package
       yum: name=https://packages.chef.io/stable/el/7/chefdk-0.17.17-1.el7.x86_64.rpm  state=present

     - name: install additional packages
       yum: name={{ item }} state=present
       with_items:
         - git
         - vim

     - name: verify chefdk installation
       command: chef verify

     - name: configure system ruby
       shell: echo 'eval "$(chef shell-init bash)"' >> /etc/profile

  - hosts: chefserver
    tasks:

     - name: get chefroot user key
       fetch: src=/root/{{ item }} dest=/root/ flat=yes fail_on_missing=yes
       with_items:
         - chefroot.pem
         - demoorg-validator.pem

  - hosts: workstation
    tasks:

     - name: the chef generate app command 
       shell: chef generate app  chef-repo

     - name: create .chef directory
       file: path=~/chef-repo/.chef state=directory mode=0755

     - name: adding .chef to gitignore
       shell: echo '.chef' >> ~/chef-repo/.gitignore

     - name: copy pem files
       copy: src=/root/{{ item }} dest=/root/chef-repo/.chef/
       with_items:
         - chefroot.pem
         - demoorg-validator.pem

     - name: copy knife.rb
       copy: src=/etc/ansible/files/knife.rb dest=/root/chef-repo/.chef/

     - name: configure ssl
       shell: cd /root/chef-repo/; knife ssl fetch
