---
automate_url:  https://packages.chef.io/stable/el/7/delivery-0.5.432-1.el7.x86_64.rpm
chefdk_url: https://packages.chef.io/stable/el/7/chefdk-0.19.6-1.el7.x86_64.rpm
chef_server_address: chefserver01.{{publicdomain}}
fqdn: chefautomate01.{{publicdomain}}

# license_file should be on ansible server
license_file: /etc/ansible/files/automate.license

# delivery_user_key_file should be on ansible server
delivery_user_key_file: "{{importdir}}/delivery.pem"

delivery_org: exampleinc
delivery_enterprise: demoent
buildnodes:
 - buildnode01.{{publicdomain}}
 - buildnode02.{{publicdomain}}
 - buildnode03.{{publicdomain}}

users:
 chefroot:
  pass: PASSWORD
  roles: admin,committer,reviewer,shipper,observer
 manager:
  pass: PASSWORD
  roles: observer
