---
  - hosts: chefautomate
    tasks:
     - name: get chef automate packages
       get_url: url=https://packages.chef.io/stable/el/7/delivery-0.5.125-1.el7.x86_64.rpm  dest=/root/

     - name: install chef automate package
       yum: name=/root/delivery-0.5.125-1.el7.x86_64.rpm  state=present

     - name: copy chef automate license file
       copy: src=/etc/ansible/license/automate.license dest=/root/

     - name: copy delivery user key file
       copy: src=/root/delivery.pem dest=/root/

     - name: setup chef automate
       command: delivery-ctl setup --license /root/automate.license  --key /root/delivery.pem --server-url https://chefserver01.example.com/organizations/autoorg --fqdn chefautomate01.example.com --enterprise demoent  --configure --no-build-node
       register: results

     - name: save results to /root/automate_cred.txt 
       local_action: copy content="{{ results.stdout }}" dest=/root/automate_cred.txt

     - name: get chefdk package
       get_url: url=https://packages.chef.io/stable/el/7/chefdk-0.17.17-1.el7.x86_64.rpm dest=/root/

     - name: copy private key for the environment
       copy: src=/etc/ansible/keys/devops.key dest=/root/

     - name: install buildnodes
       command: delivery-ctl install-build-node --fqdn {{ item }}.example.com --username centos --password none --installer /root/chefdk-0.17.17-1.el7.x86_64.rpm --ssh-identity-file /root/devops.key --port 22
       with_items:
         - buildnode01
         - buildnode02
         - buildnode03

