---

#  - name: Update packages
#    yum: name=* state=latest

  - name: Setup epel-repository
    yum: name=epel-release state=present

  - name: Install additional packages
    yum: name={{item}} state=present
    with_items:
      - wget
      - tcpdump
      - bind-utils
      - net-tools
      - git

  - name: Disable SELinux
    selinux: policy=targeted state=permissive
  
  - name: copy /etc/hosts
    copy: dest=/etc/hosts src=files/hosts
  
  - name: Configure static hostname
    hostname: name={{ hostname }} 
