---

  - name: copy /etc/hosts
    copy: dest=/etc/hosts src=files/hosts

  - name: Configure static hostname
    hostname: name={{ hostname }}

  - include: centos.yaml
    when: ansible_distribution == "CentOS"

  - include: ubuntu.yaml
    when: ansible_distribution == "Ubuntu"
