---
- hosts: workstation
  become: true
  vars_files:
   - ../config.yml
  roles:
   - chefworkstation
  tasks:
   - name: copy chefuser ssh public key to {{importdir}}
     copy: src=/home/chefuser/.ssh/id_rsa.pub dest={{importdir}}/chefuser_id_rsa.pub
     delegate_to: 127.0.0.1
