---
- hosts: workstation
  become: true
  vars_files:
   - ../config.yml
  roles:
   - chefworkstation
  tasks:
   - name: copy chefuser ssh public key to {{importdir}}
     fetch: src=/home/chefuser/.ssh/id_rsa.pub dest={{importdir}}/chefuser_id_rsa.pub
