---
# Mandatory variables for this playbook:
#  - domaintag
#

- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
   - ../config.yml
  tasks:
   - name: add infrastrucure hosts to dynamic inventory
     add_host:
      name: "{{item.name}}.{{publicdomain}}"
      groups: "{{item.groups}}"
      ansible_connection: smart
      ansible_user: "{{item.user}}"
      ansible_ssh_private_key_file: ~/{{KeyName}}.pem
     with_items:
      - { name: chefserver01,     groups: 'infrahosts,chefserver',     user: centos }
      - { name: chefautomate01,   groups: 'infrahosts,chefautomate',   user: centos }
      - { name: chefcompliance01, groups: 'infrahosts,chefcompliance', user: centos }
      - { name: chefworkstation01,groups: 'infrahosts,workstation',    user: centos }
      - { name: buildnode01,      groups: 'infrahosts',                user: centos }
      - { name: buildnode02,      groups: 'infrahosts',                user: centos }
      - { name: buildnode03,      groups: 'infrahosts',                user: centos }
      - { name: acceptance01,     groups: 'apphosts',                  user: ubuntu }
      - { name: union01,          groups: 'apphosts',                  user: ubuntu }
      - { name: rehearsal01,      groups: 'apphosts',                  user: ubuntu }
      - { name: delivered01,      groups: 'apphosts',                  user: ubuntu }
     changed_when: false

- hosts: all
  gather_facts: false
  become: false
  serial: 15
  tasks:
   - name: wait until all hosts are up and running
     wait_for: port=22 search_regex=OpenSSH delay=15 timeout=300
     delegate_to: localhost

- hosts: infrahosts,apphosts
  serial: 15
  become: true
  vars_files:
   - ../config.yml
  roles:
   - democommon

# Deploy Chef Server
- hosts: chefserver
  become: true
  vars_files:
   - ../config.yml
  roles:
   - chefserver

- include: chefworkstaion.yaml

# Deploy Chef Compliance scanner
- hosts: chefcompliance
  roles:
   - chefcompliance

- include: chefautomate.yaml

- include: configure_automate_environment.yaml
