- hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars_files:
   - ../config.yml
  tasks:
    - name: get private key information
      command: cat ~/{{KeyName}}.pem
      register: private_key

    - name: send email that chefdemo is ready
      mail:
        subject: "{{publicdomain}}: Chef Demo Environment is ready to use"
        to: "{{email}}"
        from: Li9 Demo <do-not-reply@demo.li9.com>
        body: |
          Your requests for Chef Demo Environment has been completed
          The following information is important to connect to the service:
          *) Chef Server Hostname: chefserver01.{{publicdomain}}
          *) Chef Server URL: https://chefserver01.{{publicdomain}}
          *) The following users can be used:
             - chefroot/PASSWORD (demoorg organization)
             - delivery/PASSWORD (exampleinc organization)
          *) Chef Workstation was configured on chefworkstaion01.{{publicdomain}}
          *) Chef Workstaion OS user is chefuser (please start using as shown below):
          su - chefuser
          cd che-repo1 (or chef-repo2)
          knife node list
          knife help
          *) Chef Compliance Scanner is available via URL: https://chefcompliance01.{{publicdomain}}
          *) Chef Compliance Hostname: chefcompliance01.{{publicdomain}}
          *) SSH username: ec2-user
          *) SSH access type: only using a private key
          *) SSH private key is shown below:
          {{ private_key.stdout }}
          Thank you
          //Li9 team
      when: email is defined

